"""
Data models for the Proactive Intelligence System.

This module contains all dataclass definitions for the proactive system,
including intent models, behavioral models, events, and notifications.
"""
from __future__ import annotations

import time
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Callable, Dict, List, Optional


@dataclass
class IntentModel:
    """
    Daily intent model containing active projects, deadlines, and focus mode.
    
    Generated by IntentionEngine every 6 hours by analyzing user context
    (ChromaDB memories, tasks, cron jobs, git commits, watchdog states).
    
    Attributes:
        timestamp: When this intent model was generated
        active_projects: List of currently active project names
        open_loops: List of incomplete tasks or pending items
        today_deadlines: List of deadlines due today
        focus_mode: Current focus mode ("deep_work", "meeting", "coding", "idle")
        recommended_music: Music recommendation ("lofi", "focus", "energetic", "none")
        suggested_first_action: Suggested next action for the user
    """
    timestamp: datetime
    active_projects: List[str]
    open_loops: List[str]
    today_deadlines: List[str]
    focus_mode: str  # "deep_work", "meeting", "coding", "idle"
    recommended_music: str  # "lofi", "focus", "energetic", "none"
    suggested_first_action: str


@dataclass
class BehavioralModel:
    """
    Weekly behavioral model containing learned user patterns.
    
    Generated by BehavioralPatternLearner every Sunday night by analyzing
    the last 4 weeks of behavioral fingerprints.
    
    Attributes:
        generated_at: When this behavioral model was generated
        morning_routine: Dict containing typical morning behavior patterns
        peak_coding_hours: List of time ranges when user is most productive
        typical_project_switch_time: Average time before switching projects
        never_works_on: List of time periods when user never works
        frequently_forgets: List of things user frequently forgets
    """
    generated_at: datetime
    morning_routine: Dict[str, Any]
    peak_coding_hours: List[str]
    typical_project_switch_time: str
    never_works_on: List[str]
    frequently_forgets: List[str]


@dataclass
class ProactiveEvent:
    """
    Enhanced proactive event with priority, urgency, and interrupt control.
    
    Represents a single proactive notification or action from the background
    engine. Enhanced with priority-based routing and interrupt intelligence.
    
    Attributes:
        kind: Event type ("system", "cron", "dream_epiphany", "morning_briefing", etc.)
        message: Human-readable message text
        data: Additional structured data for the event
        ts: Timestamp when event was created (epoch seconds)
        priority: Priority level ("low", "medium", "high", "critical")
        urgency: Delivery timing ("immediate", "next_idle", "next_session")
        interruptible: Whether this event can interrupt active work
        notification_id: Unique ID for deduplication
    """
    kind: str
    message: str
    data: Dict[str, Any] = field(default_factory=dict)
    ts: float = field(default_factory=time.time)
    priority: str = "medium"  # "low", "medium", "high", "critical"
    urgency: str = "next_idle"  # "immediate", "next_idle", "next_session"
    interruptible: bool = True
    notification_id: str = ""
    
    def __post_init__(self) -> None:
        """Generate notification_id if not provided."""
        if not self.notification_id:
            # Generate unique ID from kind + message + timestamp
            import hashlib
            content = f"{self.kind}:{self.message}:{self.ts}"
            self.notification_id = hashlib.sha256(content.encode()).hexdigest()[:16]


@dataclass
class BehavioralFingerprint:
    """
    Record of a single user interaction for behavioral pattern learning.
    
    Recorded after every Orchestrator interaction and stored in patterns.jsonl.
    Used by BehavioralPatternLearner to identify user patterns over time.
    
    Attributes:
        timestamp: When this interaction occurred
        interaction_type: Type of interaction ("code", "write", "search", "system")
        duration_sec: How long the interaction took in seconds
        tools_used: List of tool names used during the interaction
        context: Brief description of what the user was working on
    """
    timestamp: datetime
    interaction_type: str  # "code", "write", "search", "system"
    duration_sec: int
    tools_used: List[str]
    context: str


@dataclass
class AutoAction:
    """
    Definition of an autonomous action that can be executed automatically.
    
    Actions are classified into three classes:
    - Class A: Always automatic (silent execution)
    - Class B: Automatic with notification
    - Class C: Queued for user approval
    
    Attributes:
        action_class: Classification ("A", "B", "C")
        action_type: Type identifier (e.g., "memory_consolidate", "disk_cleanup")
        description: Human-readable description of what this action does
        execute_fn: Callable function that executes the action
        approval_required: Whether user approval is required before execution
        notification_required: Whether to notify user when executing
    """
    action_class: str  # "A", "B", "C"
    action_type: str  # "memory_consolidate", "disk_cleanup", etc.
    description: str
    execute_fn: Callable[[], Any]
    approval_required: bool
    notification_required: bool


@dataclass
class NotificationLog:
    """
    Log entry for a delivered notification.
    
    Stored in notifications.jsonl for deduplication and audit trail.
    
    Attributes:
        id: Unique notification ID (from ProactiveEvent.notification_id)
        timestamp: When the notification was delivered
        kind: Event kind (from ProactiveEvent.kind)
        priority: Priority level (from ProactiveEvent.priority)
        channels: List of channels where notification was delivered
        delivered: Whether delivery was successful
        error: Error message if delivery failed (None if successful)
    """
    id: str
    timestamp: datetime
    kind: str
    priority: str
    channels: List[str]
    delivered: bool
    error: Optional[str] = None
