"""
ANKITA Runtime Extension: random_motivation
Generates a random motivational quote from a predefined list.
Auto-generated by self_extend()
"""

import random

def random_motivation():
    quotes = [
        "Believe you can and you're halfway there.",
        "The only way to do great work is to love what you do.",
        "Success is not final, failure is not fatal: It is the courage to continue that counts.",
        "Don't watch the clock; do what it does. Keep going.",
        "Hardships often prepare ordinary people for an extraordinary destiny.",
        "Dream big and dare to fail.",
        "Act as if what you do makes a difference. It does.",
        "Keep your face always toward the sunshine—and shadows will fall behind you."
    ]
    return random.choice(quotes)